### ISSUE TITLE
More Plugin Methods

### ISSUE THREAD

**Issue by DubyaDude** [AdGoBye/AdGoBye#52]
It would be nice to have the following methods added to the plugin interface:
- Initialize - Some plugins require some initialization to be done before any patching occurs, would be nice to have this be its own method.
- PostPatch - Some plugins are purely meant to notify users when the files are done being touched. Would be nice to have this method to more accurately be able to notify users.

**Comment by regalialong** [comment]
I'm thinking about turning this into an issue to track something like 'Plugins v2'. 

#8 will require a new / extended Plugin interface anyway and I haven't seen much use of Plugins outside of AT. With that, we can bundle AT-only with an improved interface.

It's a bit difficult to gauge because I haven't gotten much direct feedback and there isn't a community space with reach such as Discord to ask on.
