### ISSUE TITLE
DB operations are being done in parallel

### ISSUE THREAD

**Issue by DubyaDude** [AdGoBye/AdGoBye#62]
Discovered some time ago, DB operations seem to not be working in parallel/async.

![Discord_z0XYjCFwSv](https://github.com/AdGoBye/AdGoBye/assets/13679909/7e40dfbf-0a69-4553-b396-af351e3e27d0)

**Comment by DubyaDude** [comment]
The class already somewhat exists, `State.IndexContext` could implement a `SaveChangesSafe` where a static object is locked so ensure saves changes don't occur at once.

**Comment by regalialong** [comment]
God damn it EF.

Apparently the multithreaded mode was supported at some point but then reverted as per https://github.com/dotnet/efcore/issues/22330#issuecomment-1291916289 since it "does not seem possible to do this safely". We also [may not share instances of DbContext](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues), which would have given us a elegant way to deal with this.

**Comment by regalialong** [comment]
Pretty sure what we're doing is a supported pattern, that's very annoying.

The cleaner way to implement this would be to pass all things that should be saved to another class and then write it in batch.
We could obviously add a mutex of some kind but that would block all threads on a single writer, I think that could pile up.
